import type { SocialClient } from "@/lib/crm/social-types"

const now = new Date().toISOString()

export const DEFAULT_SOCIAL_CLIENTS: SocialClient[] = [
  {
    id: "sc-1",
    brand: "Panadería del Centro",
    contactName: "María G.",
    contactPhone: "2645551234",
    platforms: ["instagram", "facebook"],
    plan: "growth",
    status: "activo",
    postsPerMonth: 12,
    postsDelivered: 9,
    nextDelivery: new Date(Date.now() + 2 * 86400000).toISOString(),
    notes: "Calendario mensual aprobado. Stories los martes.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sc-2",
    brand: "Constructora Norte SJ",
    contactName: "Pablo R.",
    platforms: ["instagram", "linkedin"],
    plan: "premium",
    status: "activo",
    postsPerMonth: 16,
    postsDelivered: 14,
    nextDelivery: new Date(Date.now() + 86400000).toISOString(),
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sc-3",
    brand: "Clínica Salud+",
    contactName: "Dra. López",
    platforms: ["instagram"],
    plan: "esencial",
    status: "onboarding",
    postsPerMonth: 8,
    postsDelivered: 2,
    nextDelivery: new Date(Date.now() + 5 * 86400000).toISOString(),
    notes: "Brief de tono médico en curso.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sc-4",
    brand: "Bodega Valle Fértil",
    contactName: "Tomás",
    contactPhone: "2645559876",
    platforms: ["instagram", "tiktok"],
    plan: "growth",
    status: "activo",
    postsPerMonth: 12,
    postsDelivered: 11,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sc-5",
    brand: "Estudio Jurídico Rivas",
    platforms: ["linkedin", "instagram"],
    plan: "esencial",
    status: "pausa",
    postsPerMonth: 8,
    postsDelivered: 0,
    notes: "Pausa por licencia — retoma en julio.",
    createdAt: now,
    updatedAt: now,
  },
]
